version: '3.8'
services:

  # Instância do banco de dados
  postgres:
    image: postgres:16.3
    env_file: ./env/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Instância da aplicação java
  app:
    build:
      context: .
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - 8080
    ports:
      - 8080:8080

volumes:
  postgres-data: